#!/bin/sh

REPO_URL="https://github.com/nightflyza/PureNAS.git"
TARGET_DIR="/etc/PureNAS"
BRANCH="main"

if [ ! -d "$TARGET_DIR/.git" ]; then
    rm -rf "$TARGET_DIR"
    git clone "$REPO_URL" "$TARGET_DIR" 
fi

cd "$TARGET_DIR"

if [ -f "purenas.conf" ]; then
    CONFIG_BACKUP="/tmp/purenas.conf.backup"
    cp "purenas.conf" "$CONFIG_BACKUP"
fi

git fetch origin
git reset --hard "origin/$BRANCH"
git clean -fdx

if [ -f "$CONFIG_BACKUP" ]; then
    cp "$CONFIG_BACKUP" "purenas.conf"
    rm "$CONFIG_BACKUP"
fi