#!/usr/bin/env bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../purenas.conf"

IP="$1"

arpcmd="/usr/sbin/arp"

if [ -z "$IP" ]; then
    echo "Usage: $0 <IP_ADDRESS>"
    exit 1
fi

if [ "${DISABLE_ARPFIX:-NO}" = "YES" ]; then
    echo "== DISABLE_ARPFIX is set, skipping static ARP remove for ${IP} =="
else
    ${arpcmd} -d ${IP}
    echo "== Removed static ARP entry for ${IP} =="
fi
