#!/usr/bin/env bash
set -e

IP="$1"

arpcmd="/usr/sbin/arp"

if [ -z "$IP" ]; then
    echo "Usage: $0 <IP_ADDRESS>"
    exit 1
fi

${arpcmd} -d ${IP}

echo "== Removed static ARP entry for ${IP} =="
